version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - WATCH_MODE
    ports:
      - ${ROOT_PORT}:8000
    volumes:
      - ./src/app/migrations:/project/src/app/migrations
    develop:
      watch:
        - action: sync
          path: ./src
          target: /project/src

  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
